### ISSUE TITLE
Using adapters in a multimodal model

### ISSUE THREAD

**Issue by loukasilias** [adapter-hub/adapters#636] opened 2024-01-09 10:34 UTC
Hello,

I have a model with text and images as inputs
I pass the text through BERT and images through Vision Transformers and train the multimodal model.
Is it possible to add adapter to BERT and train the multimodal model in the same way (as I train it without adapter / without changing the code of training).

Thank you.
Loukas

**Comment by calpt** [comment] 2024-01-25 20:59
Duplicate of https://github.com/adapter-hub/adapters/discussions/635.

**Closed by calpt** 2024-01-25 20:59 UTC
Labels: duplicate
