### ISSUE TITLE
WhisperAdapterModel does not support custom Whisper classifier

### ISSUE THREAD

**Issue by MRMirzahosein** [adapter-hub/adapters#768] opened 2024-12-14 09:41 UTC
## Environment info
- ` adapters ` version: 1.0.1
- Platform: Kaggle Notebook
- Python version: 3.10.14
- PyTorch version (GPU?): 2.4.0 (GPU)
- Tensorflow version (GPU?):
- Using GPU in script?:
- Using distributed or parallel set-up in script?:

## Details
I'm trying to use an adapter in my custom Whisper classifier.
The WhipserAdapterModel is implemented for ASR and cannot be used for my purpose. So, I added EmbeddingAdaptersWrapperMixin from the Adapters to my model, but it still has an error of using PEFT as the adapter.

My classifier (similar to [WhisperForAudioClassification ](https://huggingface.co/docs/transformers/v4.47.1/en/model_doc/whisper#transformers.WhisperForAudioClassification) in HuggingFace) : 

```
from adapters.model_mixin import EmbeddingAdaptersWrapperMixin
from adapters.wrappers import init

class MyWhisperForAudioClassification(EmbeddingAdaptersWrapperMixin, WhisperPreTrainedModel):
    def __init__(self, config):
        super().__init__(config)

        self.encoder = WhisperEncoder(config)

        # Initialize adapters
        init(self.encoder)
        
        num_layers = config.num_hidden_layers + 1  # transformer layers + input embeddings
        if config.use_weighted_layer_sum:
            self.layer_weights = nn.Parameter(torch.ones(num_layers) / num_layers)
        self.projector = nn.Linear(config.hidden_size, config.classifier_proj_size)
        self.classifier = nn.Linear(config.classifier_proj_size, config.num_labels)

        # Initialize weights and apply final processing
        self.post_init()

    def freeze_encoder(self):
        self.encoder._freeze_parameters()

    def get_input_embeddings(self) -> nn.Module:
        return self.encoder.get_input_embeddings()

    def set_input_embeddings(self, value: nn.Module):
        self.encoder.set_input_embeddings(value)

    def forward(
        self,
        input_features=None,
        head_mask=None,
        encoder_outputs=None,
        labels=None,
        output_attentions=None,
        output_hidden_states=None,
        return_dict=None,
    ):

        output_attentions = output_attentions if output_attentions is not None else self.config.output_attentions
        output_hidden_states = (
            output_hidden_states if output_hidden_states is not None else self.config.output_hidden_states
        )
        if self.config.use_weighted_layer_sum:
            output_hidden_states = True
        elif output_hidden_states is None:
            output_hidden_states = self.config.output_hidden_states

        return_dict = return_dict if return_dict is not None else self.config.use_return_dict

        if encoder_outputs is None:
            encoder_outputs = self.encoder(
                input_features,
                head_mask=head_mask,
                output_attentions=output_attentions,
                output_hidden_states=output_hidden_states,
                return_dict=return_dict,
            )

        if self.config.use_weighted_layer_sum:
            hidden_states = encoder_outputs[_HIDDEN_STATES_START_POSITION]
            hidden_states = torch.stack(hidden_states, dim=1)
            norm_weights = nn.functional.softmax(self.layer_weights, dim=-1)
            hidden_states = (hidden_states * norm_weights.view(-1, 1, 1)).sum(dim=1)
        else:
            hidden_states = encoder_outputs[0]

        hidden_states = self.projector(hidden_states)
        pooled_output = hidden_states.mean(dim=1)

        logits = self.classifier(pooled_output)

        loss = None

        if labels is not None:
            loss_fct = CrossEntropyLoss()
            # move labels to correct device to enable PP
            labels = labels.to(logits.device)
            loss = loss_fct(logits.view(-1, self.config.num_labels), labels.view(-1))

        if not return_dict:
            output = (logits,) + encoder_outputs[1:]
            return ((loss,) + output) if loss is not None else output
        

        return SequenceClassifierOutput(
            loss=loss,
            logits=logits,
            hidden_states=encoder_outputs.hidden_states,
            attentions=encoder_outputs.attentions,
        )
```
Then I define the model and assign a LoRA adapter to it:

```
model = MyWhisperForAudioClassification.from_pretrained(
    model_checkpoint
)

name = "whisper_LoRA"
model.add_adapter(name, config="lora")
```

Eventually, I face this error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[63], line 7
      1 model = MyWhisperForAudioClassification.from_pretrained(
      2     model_checkpoint
      3 )
      6 name = "whisper_LoRA"
----> 7 model.add_adapter(name, config="lora")

TypeError: PeftAdapterMixin.add_adapter() got an unexpected keyword argument 'config'
```
Hi @TimoImhof, Do you have any idea?

**Comment by lenglaender** [comment] 2024-12-14 15:30
Hey @MRMirzahosein, I quickly skimmed through your PR and noticed you're getting a PeftAdapterMixin error. Do you have the Hugging Face PEFT package installed? Having both installations (PEFT + Adapters) could lead to unexpected behavior. If so, please deinstall PEFT in your environment and try your code again. If this isn't the root cause of the issue, @TimoImhof can surely help you further as soon as he finds the time for it.

**Comment by MRMirzahosein** [comment] 2024-12-15 13:08
Thanks @lenglaender, I could finally solve the issue with your help.
I needed to add adapters to several Whisper modules using the mixin_whisper classes from the first [link](https://github.com/adapter-hub/adapters/blob/main/src/adapters/models/whisper/mixin_whisper.py) you sent.
I pursued the following steps:

1. Implemented `MyWhisperAttention`, `MyWhisperEncoderLayer`, and `MyWhisperEncoder` and added the LoRA adapter:
```
lora_config = LoRAConfig(r=8, use_gating=True)
adapters_config = ModelAdaptersConfig()
adapters_config.add("lora", config=lora_config)

class MyWhisperAttention(WhisperAttention, WhisperAttentionAdaptersMixin):
    def __init__(self, config):
        super().init_adapters(config, adapters_config)
        
WHISPER_ATTENTION_CLASSES = {
    "eager": MyWhisperAttention,
    "flash_attention_2": WhisperFlashAttention2,
    "sdpa": WhisperSdpaAttention,
}

class MyWhisperEncoderLayer(WhisperEncoderLayer, WhisperEncoderLayerAdaptersMixin):
    def __init__(self, config):
        super().__init__(config)
        self.init_adapters(config, adapters_config)
        
class MyWhisperEncoder(WhisperEncoder):
    def __init__(self, config):
        super().__init__(config)
        self.layers = nn.ModuleList([MyWhisperEncoderLayer(config) for _ in range(config.encoder_layers)])
```

2. Added `MyWhisperEncoder` into `MyWhisperForAudioClassification`:
```
class MyWhisperForAudioClassification(WhisperPreTrainedModel):
    def __init__(self, config):
        super().__init__(config)

        self.encoder = MyWhisperEncoder(config)
        
        num_layers = config.num_hidden_layers + 1  # transformer layers + input embeddings
        if config.use_weighted_layer_sum:
            self.layer_weights = nn.Parameter(torch.ones(num_layers) / num_layers)
        self.projector = nn.Linear(config.hidden_size, config.classifier_proj_size)
        self.classifier = nn.Linear(config.classifier_proj_size, config.num_labels)

        # Initialize weights and apply final processing
        self.post_init()

    def freeze_encoder(self):
        self.encoder._freeze_parameters()

    def get_input_embeddings(self) -> nn.Module:
        return self.encoder.get_input_embeddings()

    def set_input_embeddings(self, value: nn.Module):
        self.encoder.set_input_embeddings(value)

    def forward(
        self,
        input_features=None,
        head_mask=None,
        encoder_outputs=None,
        labels=None,
        output_attentions=None,
        output_hidden_states=None,
        return_dict=None,
    ):

        output_attentions = output_attentions if output_attentions is not None else self.config.output_attentions
        output_hidden_states = (
            output_hidden_states if output_hidden_states is not None else self.config.output_hidden_states
        )
        if self.config.use_weighted_layer_sum:
            output_hidden_states = True
        elif output_hidden_states is None:
            output_hidden_states = self.config.output_hidden_states

        return_dict = return_dict if return_dict is not None else self.config.use_return_dict

        if encoder_outputs is None:
            encoder_outputs = self.encoder(
                input_features,
                head_mask=head_mask,
                output_attentions=output_attentions,
                output_hidden_states=output_hidden_states,
                return_dict=return_dict,
            )

        if self.config.use_weighted_layer_sum:
            hidden_states = encoder_outputs[_HIDDEN_STATES_START_POSITION]
            hidden_states = torch.stack(hidden_states, dim=1)
            norm_weights = nn.functional.softmax(self.layer_weights, dim=-1)
            hidden_states = (hidden_states * norm_weights.view(-1, 1, 1)).sum(dim=1)
        else:
            hidden_states = encoder_outputs[0]

        hidden_states = self.projector(hidden_states)
        pooled_output = hidden_states.mean(dim=1)

        logits = self.classifier(pooled_output)

        loss = None

        if labels is not None:
            loss_fct = CrossEntropyLoss()
            # move labels to correct device to enable PP
            labels = labels.to(logits.device)
            loss = loss_fct(logits.view(-1, self.config.num_labels), labels.view(-1))

        if not return_dict:
            output = (logits,) + encoder_outputs[1:]
            return ((loss,) + output) if loss is not None else output
        

        return SequenceClassifierOutput(
            loss=loss,
            logits=logits,
            hidden_states=encoder_outputs.hidden_states,
            attentions=encoder_outputs.attentions,
        )


model = MyWhisperForAudioClassification.from_pretrained(
    model_checkpoint,
    config=config
)
```

**Comment by lenglaender** [comment] 2024-12-15 15:10
Glad I could help and that it works now. Wish you all the best for your master's thesis! I am closing this issue now. If you have any other problem, please open a new issue or re-open this issue if it's related.

**Closed by lenglaender** 2024-12-15 15:10 UTC
Labels: bug

**Comment by MRMirzahosein** [comment] 2024-12-16 15:38
Hi Leon, I appreciate your assistance; it meant a lot to me.
I wish you the best.
